[build]
builder = "nixpacks"
buildCommand = "npm install"
watchPatterns = ["backend/**"]

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "always"

[source]
rootDirectory = "backend"